### ISSUE TITLE
Add lookup table for Proppian functions

### ISSUE THREAD

**Issue by j-hagedorn** [j-hagedorn/trilogy#39]
@sdaranyi , you mentioned that you'd like to: "In a separate list, start collecting motifs that correspond to functions. Eg L161 and L162 would be F31 Wedding, maybe part of it F30 Punishment, whereas the root could be screened for F0 Initial situation, F1 Absentation (leaving from home)."

In order to do this, we would want to be able to join our motif table to a table of Proppian functions.  Would we want any information about the functions in this table other than [what's noted here](https://www.researchgate.net/figure/The-31-functions-of-folktales-morphology-Propp-1998_tbl3_311647729) (i.e. a table with `propp_id`, `definition`, `function`)?

**Comment by sdaranyi** [comment]
I’ll look into this today, thanks.

**Comment by j-hagedorn** [comment]
@sdaranyi  Per your comment that "section Q "Rewards and punishments" should be screened for any compliance with Proppians F30-31.", should we make it a goal to add Proppian annotations to the 'tmi' dataset's motifs?

**Comment by sdaranyi** [comment]
Absolutely, although it sounds like Lab stuff for now -- we are looking for supporting evidence to underpin Murphy's argument.

**Comment by sdaranyi** [comment]
@j-hagedorn >in order to do this, we would want to be able to join our motif table to a table of Proppian functions. Would we want any information about the functions in this table other than [what's noted here](https://www.researchgate.net/figure/The-31-functions-of-folktales-morphology-Propp-1998_tbl3_311647729) (i.e. a table with propp_id, definition, function)?

Just one item, the Initial Situation sometimes called Function 0, not in Propp's list although its existence acknowledged. In an optimal case one should be able to separate the initial situation from Absentation (F1) where the standard story begins.

**Comment by j-hagedorn** [comment]
Sounds good @sdaranyi .  I'll make a reference table and we can go from there.

Do you have Levi-Strauss' items as well?  I may as well add a table for those while we're at it.

**Comment by sdaranyi** [comment]
.> Do you have Levi-Strauss' items as well? I may as well add a table for
those while we're at it.

What do you mean by Levi-Strauss' items? The canonical formula versions?

**Comment by j-hagedorn** [comment]
Oh yes, nevermind @sdaranyi .  I forgot that it was a formula and not a categorization scheme.
