### ISSUE TITLE
Finalize graph datasets of atu_seq, atu_combos, and tmi for publication

### ISSUE THREAD

**Issue by j-hagedorn** [j-hagedorn/trilogy#42]

**Comment by sdaranyi** [comment]
Not sure if it belongs here, but the test graph for Gephi from ATU types as motif strings is heavily incomplete, having just 1824 entries in the csv. During input the variables e_atu_id and e_tale_variant must be set to string list to be read in without issues, but then the digraph will have 1943 nodes and 1824 edges -- which one of these are the types? Given that in the 'old' version we had 7052 motif string (plus I found an extra type left out for some reason), not even that number is visualized yet, not to speak of the 68K after the combinatorial explosion. 

Re the type combos, the file has 964 nodes and 4696 edges. This is probably not the final number as the 4696 is reminiscent of the number of variants in the Tales of Magic section (300-749). Again, at some point we need to extend the combos network first to the 7052 and then to the 68 K number, horrific as the results may look like, if processable at all.

**Comment by j-hagedorn** [comment]
This is the perfect place to record unexpected observations in the data, @sdaranyi .  Thank you!

**Comment by sdaranyi** [comment]
Another related issue will be to align (if they can be aligned) and visualize, at least partly, the two ATU networks, types as strings below as Layer 1, and type combinations above as Layer 2. In some tilted/under an angle fashion to relay the idea. Later on, one day two more layers might belong to this kernel: the Proppian string at the deepest level, ie Layer 0, with specific activation patterns to connect to L1, and on top, the contour layer (L4), again if possible at all. If it is, probably both the type and the combos networks would have their respective topological expressions (L4.1 and L4.2).

The current problem with contour mapping is that we have too little data. From Gephi one can extract the xy coordinates of nodes, plus their z values eg by centralities, but even many points with many coordinates seem to be not enough. I base this on the positions of 995 nodes. Because a contour map corresponds to an underlying table, we need interpolation of the in-between, potential values from actual ones, alas beyond me. What do you think? Am I missing something?

Plus, centralities are minuscule values. They can express different kinds or aspects of importance, but for L1, we have the sequence of motifs in type strings which could model the plot as elevation. Say a string with 12 motifs could start at height 12, descending from much higher above than one with say 3.

**Comment by sdaranyi** [comment]
In the current ATU type network (from atu graph.csv), we have e_atu_id but no label values, so the labels of nodes in Gephi are impossible to visualize. Likewise in the atu combos graph.csv the type labels are missing.

**Comment by j-hagedorn** [comment]
Good call, @sdaranyi .  I can add those.  Anything else that you can think of, including any new node or edge metrics?

**Comment by sdaranyi** [comment]
I'm making slow progress with Gephi, where a MultiMode Networks Transformation plugin ( https://gephi.org/plugins/#/plugin/multimode) somehow managed to add Z coordinates to the X and Y, but that is still where we used to be. What I can see is that spline, in the Apperance panel, distorts those coordinate values, but what we would need is a systematic interpolation over existing values to generate a hilly landscape. Alternatively I started to look at the simplest Mermaid graph of 510B Cap o' Rushes, to manually create a valley between two ridges to mimic the marble rolling down.

**Comment by j-hagedorn** [comment]
@sdaranyi What if we just take the empty parts in the matrix and use k-nearest neighbors or something?

**Comment by sdaranyi** [comment]
I don't know that track, so it's worth trying, go ahead.

**Comment by j-hagedorn** [comment]
Hey @sdaranyi I'm responding here to your e-mail which noted: "Thanks for the atu_graph.graphml but it is incomplete contrasted with the 7052 types (motif strings), because it has just 1943 nodes instead of the probably much more in 7052 strings. I shall experiment with this anyway but maybe already I had it."

The number of distinct motifs included in ATU tale types (i.e. `n_distinct(atu_seq$motif)`) is 3,801. 

Just to explain why the graph has fewer nodes than this: 

- `atu_graph` [removes all but the first tale variant](https://github.com/j-hagedorn/trilogy/blob/atu-network/funs/type_to_network.R#L6) for each type
- `atu_graph` also [removes all tale types with only a single motif](https://github.com/j-hagedorn/trilogy/blob/atu-network/funs/type_to_network.R#L11)

What additional questions does this raise for you?

**Comment by sdaranyi** [comment]
None for now, thanks. So we have sg like 2600 types in x variants (strings)
with 3801 motifs out of some 46 K? Sobering.

**Comment by sdaranyi** [comment]
Are those motifs in one-motif types included which are missing from the
corpus stripped on the one-motif types?

**Comment by j-hagedorn** [comment]
> Are those motifs in one-motif types included which are missing from the corpus stripped on the one-motif types?

@sdaranyi I'm not sure what you mean.  Can you please rephrase?

**Comment by sdaranyi** [comment]
There are two sets: the first has the one motif-, the second one the many
motif plots. Is there an overlap between the two?

**Comment by j-hagedorn** [comment]
Adding this cleaning note for resolution here. In `atu_seq`, remove the "." and "ff." ending the motif ID.
