### ISSUE TITLE
Determine classification structure for tales with > 1 type

### ISSUE THREAD

**Issue by j-hagedorn** [j-hagedorn/trilogy#9]
This might either be a longer tale which can be segmented into different types, or a tale which partially fits 2 types (i.e. hybrid)

**Comment by j-hagedorn** [comment]
Additional comment from anonymous reviewer: "The paper describes how tales labeled with multiple tale types were omitted from this first version. I found this to be an odd choice both because (a) this would add a significant number of tales... and (b) the additional complication of indicating would not seem to complicate the data frame very much at all. I would encourage the authors to include these tales along with their annotations.

**Comment by sdaranyi** [comment]
I think this comment was not included in the todo list, or I would remember
it, so I am somewhat baffled. (But it may be my bad, having skimmed through
things too quickly.)

On the one hand, I find it perfectly logical to have left out multilabel
ones: if we want to teach the comp how to identify motifs, why confuse it
with multiple belongings? On the other hand, upon second thought, why not
-- things will not become easier just because we ignore some facts. To (a):
is it possible to generate a list of multilabel tales vs single labels ones
as a choice between two sets, to be summed if that's what the researcher
wants? Thereby we could perhaps improve the stats for labelled sets as
training basis, plus when it comes to tests, one could compare results from
the single vs multiple labelled sets. Further, maybe this increase or added
flexibility might compensate for the loss of cca 80 titles due to
unlabelled texts.

Today I will be running around and will not have access to your mails
before tonight.

Sándor

**Comment by j-hagedorn** [comment]
Hey @sdaranyi , the issue for this one is that we currently have the data in a structure where texts are not repeated, but which allows for easy summary analysis by novices.  That is to say, it's easy to group by an `atu_id` and summarize all texts included.  If we included texts with multiple IDs, we would need to include them as nested lists, as below:

| atu_id| text|
| ------ | --- |
| c(1670, 105B) | Once upon a time and a very good time it was there was a moocow coming down along the road...|

Another concern is that the list structure here is specific to R, and different in Python, so we would stop being data tool agnostic.  Currently, you could just as easily read the dataset into `pandas` as into `dplyr`.

So, do you think we should include this in the dataset before publishing the article?

**Comment by sdaranyi** [comment]
No, I think there are limits to voluntary work. I love it when reviewers
suddenly recognize a free meal, and start asking for more. In this case, we
are even asked to pay for their free meal which tells a lot about this
world. Maybe another footnote would suffice (or if you can place it in the
running text): "We currently have the data in a structure where texts are
not repeated, but which allows for easy summary analysis by novices. The
list structure is specific to R, and different in Python, but can easily be
read into pandas and dplyr as well. Texts with multiple IDs would result in
a nested list so we would stop being data tool agnostic."

**Comment by j-hagedorn** [comment]
Removed comment from here and added text to paper.

**Comment by sdaranyi** [comment]
As a typical byproduct of the Force Atlas 2 algorithm on ATU types, we'd need to label these 'type jets' for better understanding.
![atu_type_incomplete_FA2_5_type jets](https://github.com/j-hagedorn/trilogy/assets/74593590/1c7acb83-340d-4037-ab09-a3ae7356ffd6)

**Comment by sdaranyi** [comment]
![screenshot_124107](https://github.com/j-hagedorn/trilogy/assets/74593590/2f29ccbd-2385-493b-84a0-8fd622f4a7fb)

This one is better.

**Comment by j-hagedorn** [comment]
As we approach the conference, I'm trying to prioritize efforts [within this milestone](https://github.com/j-hagedorn/trilogy/milestone/4).  This one seems like **High effort, Uncertain value**, so I'm de-prioritizing it unless you say otherwise, @sdaranyi and @salmonix .
